// <auto-generated />
using BolsaDeValores.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolsaDeValores.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230128232812_correcao")]
    partial class correcao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BolsaDeValores.Models.Acao", b =>
                {
                    b.Property<int>("AcaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcaoId"), 1L, 1);

                    b.Property<int>("CarteiraId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cotacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcaoId");

                    b.HasIndex("CarteiraId");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Acionista", b =>
                {
                    b.Property<int>("AcionistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcionistaId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Patrimonio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AcionistaId");

                    b.ToTable("Acionistas");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Carteira", b =>
                {
                    b.Property<int>("CarteiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarteiraId"), 1L, 1);

                    b.Property<int>("AcionistaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarteiraId");

                    b.HasIndex("AcionistaId");

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Corretora", b =>
                {
                    b.Property<int>("CorretoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorretoraId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PossuiOutrasCorretoras")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CorretoraId");

                    b.ToTable("Corretora");
                });

            modelBuilder.Entity("CarteiraCorretora", b =>
                {
                    b.Property<int>("CarteirasCarteiraId")
                        .HasColumnType("int");

                    b.Property<int>("CorretorasCorretoraId")
                        .HasColumnType("int");

                    b.HasKey("CarteirasCarteiraId", "CorretorasCorretoraId");

                    b.HasIndex("CorretorasCorretoraId");

                    b.ToTable("CarteiraCorretora");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Acao", b =>
                {
                    b.HasOne("BolsaDeValores.Models.Carteira", "Carteira")
                        .WithMany("Acoes")
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carteira");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Carteira", b =>
                {
                    b.HasOne("BolsaDeValores.Models.Acionista", "Acionista")
                        .WithMany()
                        .HasForeignKey("AcionistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acionista");
                });

            modelBuilder.Entity("CarteiraCorretora", b =>
                {
                    b.HasOne("BolsaDeValores.Models.Carteira", null)
                        .WithMany()
                        .HasForeignKey("CarteirasCarteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolsaDeValores.Models.Corretora", null)
                        .WithMany()
                        .HasForeignKey("CorretorasCorretoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BolsaDeValores.Models.Carteira", b =>
                {
                    b.Navigation("Acoes");
                });
#pragma warning restore 612, 618
        }
    }
}
