// <auto-generated />
using BolsaDeValores.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolsaDeValores.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230114232713_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BolsaDeValores.Models.Acionista", b =>
                {
                    b.Property<int>("AcionistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcionistaId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Patrimonio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AcionistaId");

                    b.ToTable("Acionistas");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Carteira", b =>
                {
                    b.Property<int>("CarteiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarteiraId"), 1L, 1);

                    b.Property<int>("AcionistaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarteiraId");

                    b.HasIndex("AcionistaId");

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("BolsaDeValores.Models.Carteira", b =>
                {
                    b.HasOne("BolsaDeValores.Models.Acionista", "Acionista")
                        .WithMany()
                        .HasForeignKey("AcionistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acionista");
                });
#pragma warning restore 612, 618
        }
    }
}
